version: '3.4'
services:
  frontend:
    image: node_test:1.0.0
    # build: ./frontend/
  backend:
    # image: node_test:1.0.0
    build: 
      context: ../webApp
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    restart: always
  # custom:
  #   build: ~/custom

    # services:
  nginx:
    build:
      context : .
      dockerfile: Nginx.Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"
    restart: always
  # api:
    # build: .
  #   environment:
  #     NODE_ENV: production
  #   restart: always