version: '3.4'

services:

  nginx:
    build:
      context : ./nginx/
      dockerfile: Nginx.Dockerfile
    depends_on:
      - api
    ports:
      - "9090:9090"
    restart: always


  api:
    build: .
    environment:
      NODE_ENV: production
    restart: always